version: '3.8'

services:
  frontend:
    build:
      context: ./food-microservice-app
    container_name: frontend
    image: food-microservice-app
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    restart: unless-stopped
